---
- name: Installs packages
  become: yes
  become_method: sudo
  hosts: all
  user: centos
  tasks: 
 
    - name: Install telnet
      package: 
        name: "{{item}}"
        state: present 
      with_items:
      - telnet
      - gzip
      - lftp
      - httpd  
      - vsftpd